api_key: "YOUR_TEQUILA_API_KEY_HERE"
currency: "USD"
check_days_ahead: 30

routes:
  - origin: "TAS"
    destination: "MOW"
    max_price: 200
  - origin: "TAS"
    destination: "IST"
    max_price: 180

telegram:
  enabled: true
  chat_id: "6053956251"
