#!/bin/bash
# docker-arch-analyzer.sh
# Nightly Docker architecture analysis - resource usage, junk detection, consolidation recommendations
# Run as cron job at 1:00 Asia/Tashkent

set -euo pipefail

# Configuration
REPORT_FILE="${OBSIDIAN_VAULT_PATH:-/data/obsidian/vault}/Bot/docker-architecture-report.md"
IMPROVEMENTS_DIR="${OBSIDIAN_VAULT_PATH:-/data/obsidian/vault}/Claw/possible_improvements"
TODAY=$(date '+%Y-%m-%d')
IMPLEMENTATION_FILE="$IMPROVEMENTS_DIR/docker-arch-$TODAY.md"
COMPOSE_DIR="/data/bot/openclaw-docker"
DAYS_THRESHOLD=7  # Container not used for X days = potentially junk
MEMORY_WARNING=80  # % memory usage threshold
CPU_WARNING=80    # % CPU usage threshold

# Known heavy containers that are OK (on-demand or expected high usage)
KNOWN_HEAVY=("crawl4ai" "browserless" "ollama" "litellm" "langfuse-server")

# Known on-demand containers (not running 24/7 expected)
ON_DEMAND=("crawl4ai" "stirling-pdf" "gemini-cli")

# Color codes for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "=== Docker Architecture Analysis ==="
echo "Started at: $(date)"
echo ""

# Create report header
mkdir -p "$(dirname "$REPORT_FILE")"
mkdir -p "$IMPROVEMENTS_DIR"

# Initialize implementation plan (for coder agent - detailed steps)
cat > "$IMPLEMENTATION_FILE" << 'IMPL_EOF'
# Docker Architecture Implementation Plan

**Date:** $TODAY  
**Generated by:** docker-arch-analyzer

---

## 🎯 Quick Summary

(Заполняется после анализа)

---

## 🚀 Implementation Tasks

### Priority 1: Critical (Do First)

| # | Task | Effort | Impact |
|---|------|--------|--------|

### Priority 2: High

| # | Task | Effort | Impact |
|---|------|--------|--------|

### Priority 3: Nice to Have

| # | Task | Effort | Impact |
|---|------|--------|--------|

---

## 📋 Detailed Steps

### Consolidation: Vikunja → PostgreSQL

**Why:** Single PostgreSQL instance instead of SQLite + PostgreSQL

**Steps:**
1. Connect to apps-postgres: `docker exec -it apps-postgres psql -U admin -d defaultdb`
2. Create database: `CREATE DATABASE vikunja;`
3. Update Vikunja env in docker-compose.apps.yml:
   ```yaml
   Vikunja:
     environment:
       - VIKUNJA_DATABASE_TYPE=postgres
       - VIKUNJA_DATABASE_HOST=apps-postgres
       - VIKUNJA_DATABASE_DATABASE=vikunja
       - VIKUNJA_DATABASE_USER=admin
       - VIKUNJA_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
   ```
4. Run: `docker compose -f docker-compose.apps.yml up -d vikunja`
5. Verify: Check Vikunja logs for migration success

---

### Consolidation: Langfuse → apps-postgres

**Why:** Use single PostgreSQL for all services

**Steps:**
1. Stop langfuse-server
2. Update docker-compose.yml:
   ```yaml
   langfuse-server:
     environment:
       - DATABASE_URL=postgresql://admin:${POSTGRES_PASSWORD}@apps-postgres:5432/langfuse
   ```
3. Remove langfuse-db container (but keep volume for backup)
4. Run: `docker compose up -d langfuse-server`

---

### Cleanup: Stopped Containers

**Commands:**
```bash
# List stopped containers
docker ps -a --filter "status=exited"

# Remove unused containers
docker container prune -f

# Remove unused images
docker image prune -a -f
```

---

### Alternative: Disable Langfuse (if not used)

If Langfuse observability is not actively used:
1. Comment out langfuse-server and langfuse-db in docker-compose.yml
2. Run: `docker compose down langfuse-server langfuse-db`
3. Save ~2GB RAM

---
IMPL_EOF

# Initialize main report file
cat > "$REPORT_FILE" << 'EOF'
# Docker Architecture Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')  
**Host:** $(hostname)

---

## 📊 Container Summary

| Metric | Value |
|--------|-------|
| Total Containers | $(docker ps -a --format '{{.Names}}' 2>/dev/null | wc -l) |
| Running | $(docker ps --format '{{.Names}}' 2>/dev/null | wc -l) |
| Stopped | $(docker ps -a --filter "status=exited" --format '{{.Names}}' 2>/dev/null | wc -l) |

EOF

# === SECTION 1: Resource Usage Analysis ===
echo "=== Analyzing Resource Usage ==="

# Get container stats (memory and CPU)
STATS=$(docker stats --no-stream --format '{{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}' 2>/dev/null || echo "")

cat >> "$REPORT_FILE" << 'EOF'

## 💾 Resource Usage (Current)

| Container | CPU % | Memory | Status |
|-----------|-------|--------|--------|
EOF

# Parse stats and add to report
while IFS=$'\t' read -r name cpu mem mem_perc; do
  if [ -n "$name" ]; then
    # Determine status based on usage
    mem_val=$(echo "$mem_perc" | tr -d '%')
    if [ "${mem_val:-0}" -ge "$MEMORY_WARNING" ]; then
      status="⚠️ HIGH"
    else
      status="✅ OK"
    fi
    echo "| $name | $cpu | $mem ($mem_perc) | $status |" >> "$REPORT_FILE"
  fi
done <<< "$STATS"

# === SECTION 2: Find Junk Containers ===
echo "=== Finding Potential Junk Containers ==="

cat >> "$REPORT_FILE" << 'EOF'

## 🗑️ Potential Junk Containers

*Containers not running or unused for extended period*

EOF

JUNK_FOUND=0

# Check for stopped containers
STOPPED=$(docker ps -a --filter "status=exited" --format '{{.Names}}\t{{.RunningFor}}' 2>/dev/null || true)
if [ -n "$STOPPED" ]; then
  while IFS=$'\t' read -r name age; do
    # Skip known on-demand containers
    if [[ " ${ON_DEMAND[*]} " =~ " ${name} " ]]; then
      continue
    fi
    echo "| $name | Stopped | $age |" >> "$REPORT_FILE"
    JUNK_FOUND=1
  done <<< "$STOPPED"
fi

# Check for containers with restart policy "no" (on-demand)
ON_DEMAND_CONTAINERS=$(docker ps -a --filter "restart=no" --format '{{.Names}}' 2>/dev/null || true)
if [ -n "$ON_DEMAND_CONTAINERS" ]; then
  echo "**On-demand containers (not auto-restarting):**" >> "$REPORT_FILE"
  for container in $ON_DEMAND_CONTAINERS; do
    echo "- $container (manually started when needed)" >> "$REPORT_FILE"
  done
fi

if [ $JUNK_FOUND -eq 0 ]; then
  echo "| ✅ No stopped containers found | - | - |" >> "$REPORT_FILE"
fi

# === SECTION 3: Database Consolidation Analysis ===
echo "=== Analyzing Database Consolidation ==="

cat >> "$REPORT_FILE" << 'EOF'

## 🗄️ Database Consolidation Analysis

### Current Databases
EOF

# Analyze databases
POSTGRES_RUNNING=$(docker ps --filter "name=postgres" --format '{{.Names}}' 2>/dev/null | grep -v "backup" || true)
SQLITE_CONTAINERS=$(docker ps -a --format '{{.Names}}' 2>/dev/null | xargs -I {} docker inspect {} --format '{{.Name}}:{{.Config.Env}}' 2>/dev/null | grep -i "sqlite" | cut -d: -f1 | cut -d/ -f2 || true)
CHROMA_RUNNING=$(docker ps --filter "name=chroma" --format '{{.Names}}' 2>/dev/null || true)
REDIS_RUNNING=$(docker ps --filter "name=redis" --format '{{.Names}}' 2>/dev/null || true)

echo "| Type | Container | Status |" >> "$REPORT_FILE"
echo "|-----|-----------|--------|" >> "$REPORT_FILE"

[ -n "$POSTGRES_RUNNING" ] && echo "| PostgreSQL | $(echo $POSTGRES_RUNNING | tr '\n' ', ') | Running |" >> "$REPORT_FILE"
[ -n "$SQLITE_CONTAINERS" ] && echo "| SQLite | vikunja (internal) | Running |" >> "$REPORT_FILE"
[ -n "$CHROMA_RUNNING" ] && echo "| ChromaDB | chromadb | Running |" >> "$REPORT_FILE"
[ -n "$REDIS_RUNNING" ] && echo "| Redis | redis-cache | Running |" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'

### 💡 Consolidation Recommendations

EOF

# Check for vikunja (SQLite) - could potentially use postgres
if docker ps --filter "name=vikunja" --format '{{.Names}}' 2>/dev/null | grep -q "vikunja"; then
  cat >> "$REPORT_FILE" << 'EOF'
- **Vikunja + Ryot:** Both use database. Consider migrating Vikunja to use `apps-postgres` instead of SQLite.
  - Current: Vikunja uses internal SQLite
  - Benefit: Single PostgreSQL instance, easier backup, better performance
  - Effort: Medium (requires Vikunja reconfiguration)
  
EOF
fi

# === SECTION 4: Heavy Container Analysis ===
echo "=== Analyzing Heavy Containers ==="

cat >> "$REPORT_FILE" << 'EOF'

## ⚖️ Heavy Containers (>1GB Memory)

| Container | Memory Limit | Recommendation |
|-----------|--------------|----------------|
EOF

# Get containers with memory > 1GB
HEAVY=$(docker ps --format '{{.Names}}' 2>/dev/null | xargs -I {} docker inspect {} --format '{{.Name}}:{{.HostConfig.Memory}}' 2>/dev/null | awk -F: '{if ($2 > 1073741824) print $1":"$2}' || true)

for container in $HEAVY; do
  name=$(echo $container | cut -d: -f1)
  mem_mb=$(( $(echo $container | cut -d: -f2) / 1024 / 1024 ))
  
  # Check if it's known heavy but acceptable
  if [[ " ${KNOWN_HEAVY[*]} " =~ " ${name} " ]]; then
    echo "| $name | ${mem_mb}MB | ✅ Expected (AI/ML workload) |" >> "$REPORT_FILE"
  else
    echo "| $name | ${mem_mb}MB | ⚠️ Review - consider optimization |" >> "$REPORT_FILE"
  fi
done

# === SECTION 5: Alternative Recommendations ===
echo "=== Generating Alternative Recommendations ==="

cat >> "$REPORT_FILE" << 'EOF'

## 🔄 Alternative Recommendations

### Potential Optimizations

EOF

# Check for potential alternatives
if docker ps --filter "name=searxng" --format '{{.Names}}' 2>/dev/null | grep -q "searxng"; then
  cat >> "$REPORT_FILE" << 'EOF'
- **SearXNG:** Could consider yacy (P2P search) or whoogle (Google proxy) for lighter alternative
  - Current: Full SearXNG instance
  - Alternative: Whoogle (~100MB vs ~256MB)
  
EOF
fi

if docker ps --filter "name=langfuse" --format '{{.Names}}' 2>/dev/null | grep -q "langfuse"; then
  cat >> "$REPORT_FILE" << 'EOF'
- **Langfuse:** Heavy observability stack (1GB+). Consider:
  - Disable if not actively using LLM debugging
  - Alternative: Simple logging to file + Chroma for embeddings
  - Current: Full Langfuse with PostgreSQL
  
EOF
fi

if docker ps --filter "name=uptime-kuma" --format '{{.Names}}' 2>/dev/null | grep -q "uptime-kuma"; then
  cat >> "$REPORT_FILE" << 'EOF'
- **Uptime Kuma:** Consider:
  - Health checks could be simplified
  - Alternative: Docker health checks + simple script
  
EOF
fi

# === SECTION 6: Network Analysis ===
echo "=== Analyzing Networks ==="

cat >> "$REPORT_FILE" << 'EOF'

## 🌐 Network Configuration

| Network | Containers | Type |
|---------|------------|------|
EOF

NETWORKS=$(docker network ls --format '{{.Name}}' 2>/dev/null | grep -v "bridge\|host\|none" || true)
for net in $NETWORKS; do
  containers=$(docker network inspect "$net" --format '{{range .Containers}}{{.Name}} {{end}}' 2>/dev/null | tr ' ' ',' | sed 's/,$//')
  echo "| $net | $containers | Custom |" >> "$REPORT_FILE"
done

# === SECTION 7: Port Usage ===
echo "=== Analyzing Port Usage ==="

cat >> "$REPORT_FILE" << 'EOF'

## 🔌 Port Mapping

| Container | Host Port | Container Port | Protocol |
|-----------|-----------|-----------------|----------|
EOF

docker ps --format '{{.Names}}:{{.Ports}}' 2>/dev/null | while IFS=: read -r name ports; do
  if [ -n "$ports" ]; then
    # Parse port mappings
    echo "$ports" | tr ',' '\n' | while read -r port; do
      if [[ "$port" =~ ^([0-9]+)->([0-9]+)/(.+)$ ]]; then
        echo "| $name | ${BASH_REMATCH[1]} | ${BASH_REMATCH[2]} | ${BASH_REMATCH[3]} |" >> "$REPORT_FILE"
      elif [[ "$port" =~ ^([0-9]+)/(.+)$ ]]; then
        echo "| $name | - | ${BASH_REMATCH[1]} | ${BASH_REMATCH[2]} |" >> "$REPORT_FILE"
      fi
    done
  fi
done

# === SECTION 8: Recommendations Summary ===
echo "=== Generating Summary ==="

cat >> "$REPORT_FILE" << 'EOF'

---

## 🎯 Action Items

EOF

# Count issues and generate action items
STOPPED_COUNT=$(docker ps -a --filter "status=exited" --format '{{.Names}}' 2>/dev/null | wc -l | tr -d ' ')
RUNNING_COUNT=$(docker ps --format '{{.Names}}' 2>/dev/null | wc -l | tr -d ' ')
TOTAL_MEM=$(( $(docker stats --no-stream --format '{{.MemUsage}}' 2>/dev/null | awk '{sum+=$1} END {print sum}' | tr -d 'MiGi') ))

cat >> "$REPORT_FILE" << EOF
### Summary
- **Total Containers:** $(docker ps -a --format '{{.Names}}' 2>/dev/null | wc -l | tr -d ' ')
- **Running:** $RUNNING_COUNT
- **Stopped/Exited:** $STOPPED_COUNT

### Immediate Actions
EOF

if [ "$STOPPED_COUNT" -gt 3 ]; then
  echo "- Consider cleaning up stopped containers: \`docker container prune -f\`" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << 'EOF'
- Review heavy containers if not actively used
- Consider database consolidation if storage is a concern

EOF

# === Final output ===
echo ""
echo "=== Analysis Complete ==="
echo "Report saved to: $REPORT_FILE"
echo ""
echo "Summary:"
echo "- Total containers: $(docker ps -a --format '{{.Names}}' 2>/dev/null | wc -l)"
echo "- Running: $(docker ps --format '{{.Names}}' 2>/dev/null | wc -l)"
echo "- Stopped: $(docker ps -a --filter "status=exited" --format '{{.Names}}' 2>/dev/null | wc -l)"

# Output for cron (only if there are issues)
if [ "$STOPPED_COUNT" -gt 3 ]; then
  echo ""
  echo "⚠️ Found $STOPPED_COUNT stopped containers - consider cleanup"
fi

# Generate brief summary for Telegram
SUMMARY_FILE="/tmp/docker-arch-summary.txt"
cat > "$SUMMARY_FILE" << EOF
🐳 Docker Architecture Report — $TODAY

📊 Контейнеры: $(docker ps -a --format '{{.Names}}' 2>/dev/null | wc -l) всего, $(docker ps --format '{{.Names}}' 2>/dev/null | wc -l) запущено, $STOPPED_COUNT остановлено

🎯 Ключевые находки:
EOF

# Add findings to summary
if docker ps --filter "name=vikunja" --format '{{.Names}}' 2>/dev/null | grep -q "vikunja"; then
  echo "- Vikunja использует SQLite — можно мигрировать на PostgreSQL" >> "$SUMMARY_FILE"
fi

if docker ps --filter "name=langfuse" --format '{{.Names}}' 2>/dev/null | grep -q "langfuse"; then
  echo "- Langfuse работает на отдельном PostgreSQL — можно объединить с apps-postgres" >> "$SUMMARY_FILE"
fi

if [ "$STOPPED_COUNT" -gt 3 ]; then
  echo "- $STOPPED_COUNT остановленных контейнеров — почистить?" >> "$SUMMARY_FILE"
fi

echo "" >> "$SUMMARY_FILE"
echo "📄 Полный отчёт: docker-architecture-report.md" >> "$SUMMARY_FILE"
echo "📋 План реализации: Claw/possible_improvements/docker-arch-$TODAY.md" >> "$SUMMARY_FILE"

# Output the summary
echo ""
cat "$SUMMARY_FILE"
