#!/bin/bash
# morning_digest.sh — Unified Morning Digest for OpenClaw
# Creates full report in Obsidian + short Telegram summary
# Telegram: MAX 5 lines, with "Подробнее" button to Obsidian note

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Data directory for JSON files
DATA_DIR="/data/bot/openclaw-docker/data"
mkdir -p "$DATA_DIR"

# Portfolio tracker path
PORTFOLIO_TRACKER="/home/node/.openclaw/skills/crypto_monitor/portfolio_tracker.py"

# Create default JSON files if they don't exist
if [ ! -f "$DATA_DIR/crypto_radar.json" ]; then
    echo '{"status": "no_data", "message": "Crypto radar has not run yet", "timestamp": null}' > "$DATA_DIR/crypto_radar.json"
fi

if [ ! -f "$DATA_DIR/telegram_monitor.json" ]; then
    echo '{"status": "no_data", "message": "Telegram monitor has not run yet", "channels_checked": 0, "posts_found": 0}' > "$DATA_DIR/telegram_monitor.json"
fi

# ========== CONFIG ==========
VAULT_PATH="${USER_VAULT_PATH:-/data/obsidian/vault}"
TODAY=$(date '+%Y-%m-%d')
REPORT_DATE=$(date '+%d %b %Y')
REPORT_PATH="$VAULT_PATH/Bot/morning-reports/$TODAY.md"
mkdir -p "$(dirname "$REPORT_PATH")"

# ========== GENERATE FULL REPORT ==========
{
echo "# 🌅 Morning Report — $REPORT_DATE"
echo ""
echo "Generated: $(date '+%Y-%m-%d %H:%M:%S')"
echo "---"
echo ""

# SECTION 1: Crypto Radar
echo "## 💰 Crypto Radar"
if [ -f "$DATA_DIR/crypto_radar.json" ]; then
    cat "$DATA_DIR/crypto_radar.json" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    if data.get('status') == 'ok':
        p = data.get('portfolio', {})
        m = data.get('market', {})
        print(f\"- **Портфель:** \${p.get('total_equity', 'N/A')} USDT\")
        print(f\"- **Свободно:** \${p.get('available', 'N/A')} USDT\")
        print(f\"- **BTC:** \${m.get('btc', {}).get('price', 'N/A')} (\${m.get('btc', {}).get('change_24h', 'N/A')}%))\")
        print(f\"- **ETH:** \${m.get('eth', {}).get('price', 'N/A')} (\${m.get('eth', {}).get('change_24h', 'N/A')}%))\")
        print(f\"- **SOL:** \${m.get('sol', {}).get('price', 'N/A')} (\${m.get('sol', {}).get('change_24h', 'N/A')}%)}\")
        print(f\"- **Сигнал:** \${data.get('signal', 'N/A')}\")
        print(f\"- **Sentiment:** \${data.get('sentiment', {}).get('score', 'N/A')}\")
    else:
        print(f\"- ⚠️ {data.get('message', 'No data')}\")
except Exception as e:
    print(f\"- ⚠️ Error: {e}\")
" 2>/dev/null || echo "- (Failed to read crypto data)"
else
    echo "- (Crypto radar data file not found)"
fi
echo ""

# SECTION 2: System Status
echo "## 🖥️ System Status"
echo "### Docker Containers"
docker ps --format 'table {{.Names}}\t{{.Status}}' 2>/dev/null | head -n 8 || echo "- (Docker unavailable)"
echo ""
echo "### Resources"
disk_info=$(df -h / 2>/dev/null | tail -n 1 | awk '{print $3 " / " $2 " (" $5 " used)"}' || echo "N/A")
echo "- **Disk:** $disk_info"
mem_info=$(free -h 2>/dev/null | awk '/^Mem:/ {print $3 " / " $2}' || echo "N/A")
echo "- **Memory:** $mem_info"
echo ""

# SECTION 3: Alerts (if any)
echo "## ⚠️ Alerts"
ALERT_COUNT=0

# Check cron errors
errors=$(cat /data/bot/openclaw-docker/cron/jobs.json 2>/dev/null | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    err_jobs = [j for j in data.get('jobs', []) if j.get('state', {}).get('consecutiveErrors', 0) > 0]
    for j in err_jobs[:5]:
        print(f\"- ⚠️ {j.get('name', 'Unknown')}: {j.get('state', {}).get('lastError', 'Unknown error')}\")
except: pass
" 2>/dev/null || true)

if [ -n "$errors" ]; then
    echo "$errors"
    ALERT_COUNT=1
fi

if [ $ALERT_COUNT -eq 0 ]; then
    echo "- ✅ No active alerts"
fi
echo ""

# SECTION 4: Inbox Summary
echo "## 📬 Inbox"
PENDING_COUNT=$(grep -r '\- \[ \]' "$VAULT_PATH" --include='*.md' 2>/dev/null | wc -l | tr -d ' ')
INBOX_COUNT=$(find "$VAULT_PATH/Inbox" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
echo "- **Pending tasks:** $PENDING_COUNT"
echo "- **Inbox files:** $INBOX_COUNT"
echo ""

# SECTION 5: Calendar Today
echo "## 📅 Today"
if [ -f "/home/node/.openclaw/shared/google_token.json" ]; then
    bash /data/bot/openclaw-docker/scripts/gcal.sh today 2>/dev/null | head -10 || echo "- (Calendar unavailable)"
else
    echo "- (Google not authorized)"
fi
echo ""

# SECTION 6: Quick Links
echo "## 🔗 Quick Links"
echo "- [[morning-reports/$TODAY|Today Report]] | [[error-log|Error Log]] | [[today-session|Sessions]]"
echo ""

echo "---"
echo "*Generated by OpenClaw Morning Digest*"
} > "$REPORT_PATH"

echo "Report created: $REPORT_PATH"

# ========== GENERATE SHORT TELEGRAM SUMMARY ==========
TELEGRAM_MSG=$(python3 -c "
import json

# Read crypto data
crypto_data = {}
try:
    with open('$DATA_DIR/crypto_radar.json') as f:
        crypto_data = json.load(f)
except: pass

# Build short message (MAX 5 lines)
lines = []
lines.append('🌅 Morning Digest — $REPORT_DATE')

# Crypto line
if crypto_data.get('status') == 'ok':
    p = crypto_data.get('portfolio', {})
    m = crypto_data.get('market', {})
    btc_price = m.get('btc', {}).get('price', 'N/A')[:8]
    btc_chg = m.get('btc', {}).get('change_24h', '0')
    signal = crypto_data.get('signal', '-')
    total = p.get('total_equity', 'N/A')[:10]
    lines.append(f'💰 {total} USDT | BTC {btc_price} ({btc_chg}%)')
    lines.append(f'🎯 {signal}')
else:
    lines.append('💰 Crypto: No data')

# System line
import subprocess
try:
    result = subprocess.run(['docker', 'ps', '--format', '{{.Names}}'], capture_output=True, text=True)
    containers = len(result.stdout.strip().split('\n')) if result.stdout.strip() else 0
    lines.append(f'🐳 Docker: {containers} containers running')
except:
    lines.append('🐳 Docker: unavailable')

# Alerts
import json as j
try:
    with open('/data/bot/openclaw-docker/cron/jobs.json') as f:
        jobs = j.load(f).get('jobs', [])
    errors = [j for j in jobs if j.get('state', {}).get('consecutiveErrors', 0) > 0]
    if errors:
        lines.append(f'⚠️ {len(errors)} cron error(s)')
    else:
        lines.append('✅ All systems OK')
except:
    lines.append('✅ Systems: check failed')

print('\\n'.join(lines))
")

echo ""
echo "=== TELEGRAM MESSAGE ==="
echo "$TELEGRAM_MSG"
echo "=== END TELEGRAM ==="

# ========== NOTIFY TELEGRAM ==========
NOTIFY_SCRIPT="/data/bot/openclaw-docker/skills/telegram/notify.py"
if [ -f "$NOTIFY_SCRIPT" ]; then
    python3 "$NOTIFY_SCRIPT" "$TELEGRAM_MSG" --chat-id "6053956251" 2>/dev/null || true
fi

exit 0
