tunnel: 2a6133f8-bca9-4b5c-9aab-0800a8502db9
ingress:
  - hostname: sure.volamoks.store
    service: http://host.docker.internal:3002
  - hostname: sims.volamoks.store
    service: http://192.168.147.20:5174
  - hostname: tasks.volamoks.store
    service: http://host.docker.internal:3456
  - hostname: budget.volamoks.store
    service: http://host.docker.internal:5006
  - hostname: chat.volamoks.store
    service: http://host.docker.internal:3005
  - hostname: vault.volamoks.store
    service: http://host.docker.internal:7080
  - hostname: bot.volamoks.store
    service: http://host.docker.internal:7090
  - service: http_status:404
