"""
Shared models for OpenClaw skills.

This module contains unified dataclasses for market data, alerts, signals, and opportunities.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List, Dict, Any
from enum import Enum


class SignalType(Enum):
    """Types of signals that can be generated."""
    PRICE_SPIKE = "price_spike"
    RSI_OVERSOLD = "rsi_oversold"
    RSI_OVERBOUGHT = "rsi_overbought"
    VOLUME_ANOMALY = "volume_anomaly"
    FEAR_GREED = "fear_greed"
    FUNDING = "funding"
    OI = "oi"


class SignalDirection(Enum):
    """Direction of market movement."""
    UP = "up"
    DOWN = "down"
    NEUTRAL = "neutral"


class SignalStatus(Enum):
    """Status of a signal lifecycle."""
    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass
class TickerData:
    """Real-time ticker data for a symbol."""
    symbol: str
    price: float
    change_24h: float
    volume_24h: float
    timestamp: datetime


@dataclass
class KlinesData:
    """Candlestick (kline) data for a symbol."""
    symbol: str
    interval: str
    klines: List[Dict[str, Any]]
    timestamp: datetime


@dataclass
class FundingData:
    """Funding rate data for perpetual contracts."""
    symbol: str
    funding_rate: float
    funding_timestamp: datetime


@dataclass
class OIData:
    """Open Interest data for a symbol."""
    symbol: str
    open_interest: float
    change_24h: float


@dataclass
class Alert:
    """Alert generated by the monitoring system."""
    id: str
    type: SignalType
    symbol: str
    direction: SignalDirection
    price: float
    change_pct: float
    threshold: float
    reason: str
    confidence: float
    timestamp: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_telegram_message(self) -> str:
        """Format alert as a Telegram message."""
        direction_emoji = "📈" if self.direction == SignalDirection.UP else "📉" if self.direction == SignalDirection.DOWN else "➡️"
        type_emoji = {
            SignalType.PRICE_SPIKE: "🚀",
            SignalType.RSI_OVERSOLD: "🔻",
            SignalType.RSI_OVERBOUGHT: "🔺",
            SignalType.VOLUME_ANOMALY: "📊",
            SignalType.FEAR_GREED: "😱",
            SignalType.FUNDING: "💰",
            SignalType.OI: "📈",
        }.get(self.type, "⚠️")

        message = (
            f"{type_emoji} *ALERT: {self.symbol}*\n"
            f"{direction_emoji} Direction: {self.direction.value.upper()}\n"
            f"💵 Price: ${self.price:,.2f}\n"
            f"📊 Change: {self.change_pct:+.2f}%\n"
            f"🎯 Threshold: {self.threshold:.2f}%\n"
            f"🧠 Confidence: {self.confidence:.0%}\n"
            f"📝 Reason: {self.reason}\n"
            f"🕒 Time: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}"
        )

        if self.metadata:
            extra = "\n".join(f"{k}: {v}" for k, v in self.metadata.items())
            message += f"\n\n📎 Details:\n{extra}"

        return message


@dataclass
class Signal:
    """Trading signal with tracking and results."""
    id: str
    type: SignalType
    symbol: str
    direction: SignalDirection
    price: float
    reason: str
    confidence: float
    source: str
    status: SignalStatus
    timestamp: datetime
    result_24h: Optional[float] = None
    result_7d: Optional[float] = None
    result_30d: Optional[float] = None
    user_reaction: Optional[str] = None


@dataclass
class Opportunity:
    """Trading opportunity detected by the screener."""
    symbol: str
    type: SignalType
    score: float  # 0-100
    rsi: Optional[float]
    volume_change_pct: Optional[float]
    price_change_pct: Optional[float]
    reason: str
    timestamp: datetime

    def __lt__(self, other: "Opportunity") -> bool:
        """Compare opportunities by score (for sorting)."""
        return self.score < other.score

    def __gt__(self, other: "Opportunity") -> bool:
        """Compare opportunities by score (for sorting)."""
        return self.score > other.score

    def __eq__(self, other: object) -> bool:
        """Check if two opportunities are equal."""
        if not isinstance(other, Opportunity):
            return NotImplemented
        return self.symbol == other.symbol and self.type == other.type

    def __hash__(self) -> int:
        """Hash for use in sets and dicts."""
        return hash((self.symbol, self.type, self.timestamp))
